security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        AppBundle\Entity\User: bcrypt
    providers:
        our_users:
            entity: { class: AppBundle\Entity\User, property: username }
    firewalls:
        main:
            anonymous: ~
            form_login:
                login_path: login
                check_path: login_check
            logout:
                path: /logout
                target: /